Fix issue with new versions of Chart.js
Fixes an issue that occurs when using new verisions of Chart.js, since their api has changed.

The error: `Uncaught TypeError: (intermediate value).Line is not a function`